#  Lesson 1 - Intro, Concepts & Data Types

# 1 - Introduction

## 1.1 Why Python

![Python Logo](https://www.python.org/static/img/python-logo.png)

- #1 Most starred language on GitHub (https://madnight.github.io/githut)

- An **interpreted**, **high-level** and **general-purpose** programming language.

- Commonly used for  **Scientific Computing** and **Data Science**

## 1.2 Colab & Notebooks

- Dynamic

- Interactive

- Nice for presentation

### Mode

1. View Mode

2. Edit Mode

### Common hotkeys

In View Mode

- Press `B` to insert new cell **below**

- Press `A` to insert new cell **above**


In Edit Mode
- Press `Esc` to switch back to view mode

- Press `Ctrl + Enter` to execute the cell

- Press `Ctrl + /` to comment code

# 2 - Basic Concepts

## 2.1 Calculations

|       Name       | Operator |
|:----------------:|:--------:|
|     Addition     |     +    |
|    Subtraction   |     -    |
|  Multiplication  |     *    |
|     Division     |     /    |
|  Exponentiation  |    **    |
|      Modulo      |     %    |
| Integer Division |    //    |

Division can throw its own special error `ZeroDivisionError` when attempting to divide by 0

In [ ]:
# Example of calculating maths with Python:

1 + 2 * 3

In [ ]:
# Example of ZeroDivisionError:

1/0

**Exercise**
> Try to calculate:  $ 2^3 \times 7 + \frac{14}{300} $

In [1]:
# Type your code below
2**3*7+14/300

56.04666666666667

## 2.2 Strings
Computer programmers refer to blocks of text as strings.

In Python a string is either surrounded by
- single quotes: `'Hello world'`, or
- double quotes: `"Hello world"`

In [ ]:
# Example of strings:

'Hello World'
"Hello World"

'Hello World'

**Exercise**
> Type your name as a String in Python

In [2]:
# Type your code below
print("Shih Ting Ting")

Shih Ting Ting

### Escaping

How to add a quotation mark into the string?

There are 2 methods:
- One way is to use an alternative quote for the string. (e.g. `"'"`, `'"'`)
- The better way is to use `\` to escape the character!

When Python sees the forward slash `\`, it interprets the following character(s) in the alternative way.

In the quotation mark case, the escaped quotation mark `\'` is no longer seen as the end of string.

In [6]:
# Example of escaped quotation mark

'"'
"It\"s my house"

'It"s my house'

### Multi-line Strings

By using three quote-marks (`"""` or `'''`) instead of one, we tell the program that the string doesn’t end until the next triple-quote.

**Exercise**

> Declare the following poem as a multi-line string:<br />
```In me thou see’st the glowing of such fire,
That on the ashes of his youth doth lie,
As the death-bed whereon it must expire,
Consum’d with that which it was nourish’d by
```

In [14]:
# Type your code below
"""That on the ashes of his youth doth lie,
As the death-bed whereon it must expire,
Consum’d with that which it was nourish’d by"""

'That on the ashes of his youth doth lie,\nAs the death-bed whereon it must expire,\nConsum’d with that which it was nourish’d by'

## 2.3 Variable

![Variable Analogy](https://miro.medium.com/max/10974/1*Px7h03Ih7B5QZu4KQpSEoQ.png)

- When there is a data we need to remember and reuse, we can create a variable which can store a value.

- We can image variables as labeld boxes

- In Python, we assign variables by using the equals sign (=).

- Important rules to bear in mind:

    - Variable names are **case sensitive**

    - The **first character** must not be a number

    - You cannot use **reserved keywords** to name your variables

```
False	await	else	import	pass
None	break	except	in	raise
True	class	finally	is	return
and	continue	for	lambda	try
as	def	from	nonlocal	while
assert	del	global	not	with
async	elif	if	or	yield
```

In [ ]:
# Example of assigning variables
number = 123
text = "Hello World!"

**Exercise**
> Assign your favourite breakfast as a string to a varialble called `my_favorite_breakfast`

In [15]:
# Type your code below
my_favorite_breakfast="bread"
print(my_favorite_breakfast)

bread

## 2.4 Print
- In Python, the `print()` function is used to tell a computer to talk.
- The escaped characters such as `\n` becomes an actual new line.

In [16]:
# Example of printing "Hello World"

print("Hello World!")

Hello World!

You can also print out a variable

In [17]:
# Example of printing a variable

greeting = "Good Morning!"
print(greeting)

Good Morning!

**Exercise**
> Print your favourite breakfast saved in `my_favorite_breakfast`

In [18]:
# Type your code below
print(my_favorite_breakfast)

bread

## 2.5 Updating Variables

- Performing calculation on variables does not change the variable
- We can update a variable using the = sign

In [19]:
# Example of updating a variable

num = 8
print("Num:", num)
num = num ** 2
print("Updated Num:", num)

Num: 8
Updated Num: 64

**Exercise**
> To calculate an area of a rectangle, you need `width` and `height`<br />
> 1. Assign a 30 to `width` and 50 to `height`
> 2. Calculate the area and save the result to `area`
> 3. Print the area

In [20]:
# Type your code below
width=30
height=50
area=width*height
print(area)

1500

**Exercise**
> Now we have two variables <br>
> `a=1` and `b=2`<br>
> How to swap the content of `a` and `b`?

In [23]:
# Type your code below
a = 1
b = 2
c=a
a=b
b=c
print(a) #a=2
print(b) #b=1

2
1

### The shorthand method

When you have a number saved in a variable and want to add to the current value of the variable, you can use the += (plus-equals) operator.

Similarly, the shorthand works for other operators such as `-`, `*`, etc.

In [24]:
# Instead of writing
number = 1
number = number + 2
number = number * 3
print(number) # Prints 9

# You can write
number = 1
number += 2
number *= 3

print(number) # Prints 9

9
9

In [ ]:
# Try yourself!

## 2.6. Comment
Text written in a program but not run by the computer is called a comment. Python interprets anything after a # as a comment.

In [ ]:
# Example of comments: <-- This is a comment too!

# This is a comment
# It is for human and Python will ignore it

**Exercise**
> Write a comment describing the first program you want to write!

In [ ]:
# Type your comment below

## 2.7 Errors

- Python refers mistakes as errors and will point to the location where an error occurred with the `^` character.

- The process of correcting the errors is called 'debugging'.

Some of the common errors that we encounter while writing Python are `SyntaxError` and `NameError`.

`SyntaxError` means there is something wrong with the way your program is written - punctuation that does not belong, a command where it is not expected, or a missing parenthesis can all trigger a SyntaxError.

A `NameError` occurs when the Python interpreter sees a word it does not recognize. Code that contains something that looks like a variable but was never defined will throw a NameError.

In [25]:
# Example of SyntaxError

1 2 3

SyntaxError: ignored

In [26]:
# Example of NameError

print(some_undeclared_variable)

NameError: ignored

In [27]:
# Example of IndexError

some_list = [1, 2, 3]
some_list[4]

IndexError: ignored

**Exercise**
> Print a string opened with double quote `"` and close with single quote `'`

In [29]:
# Type your code below
string='Hello'
print(string)

Hello

## 2.8 Concatenation

- The `+` operator can also 'add' two strings.

- The process of combining two strings is called string concatenation.

- Performing string concatenation creates a brand new string comprised of the first string’s contents followed by the second string’s contents

**Caution:** If you want to concatenate a string with a number you will need to make the number a string first by using the `str()` function

In [30]:
# Example

# The words are concatenated together by the + operator
print('Hello ' + 'World!')

# Numbers must be converted to str if + is used
print('攞你命' + str(3000))

Hello World!
攞你命3000

**Exercise**
> Concatenate the strings and save the message they form in the variable `message`

In [35]:
str1 = "Danger "
str2 = "Education"

# Type your code below
print(str1+str2)

Danger Education

**Exercise**
> Tell me your age by assigning an integer to variable `age` and print it in the following format:
> ```
My age is <your age here>
```

In [36]:
# Type your code below
age=int(22)
print("My age is",age)

My age is 22

## 2.9 String formating

When we want to print a sentence with variable inside, we can use concatenation.

In [37]:
# Example of long sentence with string concatenation

height_in_meter = 1.8
number_of_arms = 2
number_of_hands = 2
number_of_fingers = 10

print('I am ' + str(height_in_meter) + 'm tall. I have ' + str(number_of_arms) + ' arms, ' + str(number_of_hands) + ' hands and ' + str(number_of_fingers) + ' fingers.')

I am 1.8m tall. I have 2 arms, 2 hands and 10 fingers.

**BUT!** It's not nice at all.

Ugly isn't it?

Here comes string formating, it allows you to create the sentence first, then insert the variables you want.

**String formating version 1: The format function**

In [38]:
# Example of .format()

print('I am {a}m tall. I have {b} arms, {c} hands and {d} fingers.'.format(
    a=height_in_meter,
    b=number_of_arms,
    c=number_of_hands,
    d=number_of_fingers
))

I am 1.8m tall. I have 2 arms, 2 hands and 10 fingers.

**String formating version 2: f-String**

In [ ]:
# Example of f-string

print(f'I am {height_in_meter}m tall. I have {number_of_arms} arms, {number_of_hands} hands and {number_of_fingers} fingers.')

**Exercise**
> Tell me your age again with both formatting methods

```
My age is <your age here>
```

In [40]:
# Type your code below
#Method1
age=22
print('My age is {a}'.format(
    a=age
))

#Method2
age=22
print(f'My age is {age}')

My age is 22
My age is 22

# 3 - Data Types

There are differnt data types in Python that helps us to fulfill different purposes.

We introduce some common ones here:

**Primitive types:**

- int
- float
- string
- Boolean

**Compound types:**

- List
- Tuple
- Set
- Dictionary

You will encounter much more along the journey and even be able to create your own type!

To check the type of any names, we can use the built in function `type()`

In [43]:
# Example of using type() function to check type of data

print("Type of 1:", type(1))
print("Type of 1.0:", type(1.0))
print("Type of '1':", type('1'))
print("TYpe of True", type(True))

Type of 1: <class 'int'>
Type of 1.0: <class 'float'>
Type of '1': <class 'str'>
TYpe of True <class 'bool'>

## 3.1 Numeric Types

Python has a few numeric data types:

An integer, or `int`, is a whole number. It has no decimal point and contains all counting numbers (1, 2, 3, …) as well as their negative counterparts and the number 0.

A floating-point number, or a `float`, is a decimal number. It can be used to represent fractional quantities as well as precise measurements.

You can cast numbers in to int / float by using the corresponding constructor.

In [ ]:
# Example of casting numbers into int or float

some_int = 5
some_float = 6.0

print("Cast some_int into float:", float(some_int))
print("Cast some_float into int:", int(some_float))

Cast some_int into float: 5.0
Cast some_float into int: 6

**Exercise**
> 1. Assign an integer `1` to a variable and print it
2. Assign a float `1.0` to another variable, add `3` to it and print it

In [44]:
# Type your code below
a=int(1)
print(a)
b=1.0
print(float(b)+3)

1
4.0

## 3.2 Boolean

- Only 2 possible values: True or False (Notice the first character **must** be in capital)

- Works well with the `AND`, `OR`, `NOT` operators

- Be careful not to enclose the boolean value with quotation marks

In [45]:
# Example of a boolean

print(True, type(True))
print(False, type(False))

True <class 'bool'>
False <class 'bool'>

## 3.3 List

- Enclose with square brackets `[` and `]`

- Unlike the other languages, it supports different data types within the same list.

- Orders are respected

- Lists are "mutable"

In [ ]:
# Example of declaring lists

some_list = [1, 2, 3, 4, 5]
print("some_list:", some_list, type(some_list))

another_list = [1, 'a', 2.0, False]
print("another_list:", another_list, type(another_list))

some_list: [1, 2, 3, 4, 5] <class 'list'>
another_list: [1, 'a', 2.0, False] <class 'list'>

In [ ]:
# Example to show that lists are mutable

some_list = [1, 2, 3]
print("some_list:", some_list)
some_list.append(999) # Add an item to the end of the list
some_list[0] = 'a' # Change the first item of the list to "a"
print("some_list:", some_list)

some_list: [1, 2, 3]
some_list: ['a', 2, 3, 999]

## 3.4 Tuple
- Identified by the comma `,` but usually enclosed with brackets `(` and `)`

- Similar to lists, orders are respected and different data types within the same tuple is supported

- However, tuples are immutable

In [ ]:
# Example of declaring tuple

some_tuple = (1, 'a', 2.0, False)
print("some_tuple:", some_tuple, type(some_tuple))


# It is still the same tuple even brackets are not provided
same_tuple = 1, 'a', 2.0, False
print("same_tuple:", same_tuple, type(same_tuple))

some_tuple: (1, 'a', 2.0, False) <class 'tuple'>
same_tuple: (1, 'a', 2.0, False) <class 'tuple'>

In [47]:
# Example of TypeError when trying to mutate a tuple

some_tuple = [1, 2, 3]
print("some_tuple:", some_tuple)
some_tuple[0] = 'a' # Trying to mutate a tuple will cause error
print("some_tuple:", some_tuple) # This line won't run since an exception was raised

some_tuple: [1, 2, 3]
some_tuple: ['a', 2, 3]

**Special Property of tuple - Auto unpack**
```python
x = (1, 2)
var1, var2 = x
```

An important mechanism to support multiple-variable passing (we will talk about this more in topic of function)

**Exercise (Again!)**
> Now we have two variables <br>
> `a=1` and `b=2`<br>
> How to swap the content of `a` and `b`?


Solution:
```python
a = 1
b = 2
a, b = (b, a)
```

Explanation:
We pack two values into a tuple, then make use of the auto unpack to fill back up `a` and `b`.

## 3.5 Set
- Use set() constructor to create a set

- It is mutable

- Orders are not respected and duplicated items are removed

In [ ]:
# Example of casting a list into set

some_set = set([1, 2, 2, 3, 3, 3, 4])
print("some_set:", some_set) # Duplicated items will be removed

some_set.remove(3) # Trying to mutate the set by removing items
print("some_set:", some_set)

some_set: {1, 2, 3, 4}
some_set: {1, 2, 4}

In [ ]:
# Example of TypeError when accessing the 'first' item in the set

some_set = set([1, 2])
print(some_set[0]) # Error raised since set has no orders

TypeError: ignored

## 3.6 Dictionaries

- Use `dict()` constructor or curly brackets `{` and `}` to create dictionaries

- In a real dictionary, there are words (keys) and their definitions (values). Dictionaries stores key-value pairs.

- Mutable and orders are not respected

- It is very common and we will have a lesson focusing on dictionaries in the future.

In [48]:
# Example of creating a dictionary

some_dict = {
    "key1": "value1",
    123: "value of key 123",
    "key2": ["Dictionary", "value", "can", "be", "lists"],
    "key3": {
        "even": "another dictionary!"
    }
}

print(some_dict)

{'key1': 'value1', 123: 'value of key 123', 'key2': ['Dictionary', 'value', 'can', 'be', 'lists'], 'key3': {'even': 'another dictionary!'}}